baseurl      = "https://pooper.net.au/"
title        = "Cameron Hall"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

PygmentsCodeFences = true
PygmentsStyle = "monokai"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:title/"

[author]
  name = "Cameron Hall"

[blackfriday]
  hrefTargetBlank = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Passionate about..."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "personal blog, information"
  keywords = "homepage, blog, startpage"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

[params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[[params.social]]
    name = "email"
    url  = "mailto:cameron@pooper.net.au"

[[params.social]]
    name = "github"
    url  = "https://github.com/dickpepperfield"

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/cameron-hall-97147b1b1/"

[languages]
  [languages.en]
    title = "Cameron Hall"
    subtitle = "Welcome"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "cv/"
  [[menu.main]]
    identifier = "login"
    name       = "Login"
    url        = "https://secure.pnet.app"
