baseURL = "https://pooper.net.au"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-AU"
summaryLength = 0
theme = "congo"
title = "pooper.net.au â€” @me"
[author]
bio = "Making content is hard."
image = "images/author.png"
name = "pepperfield"
[[author.links]]
email = "mailto:cameron@pooper.net.au"
[[author.links]]
github = "https://github.com/dickpepperfield"
[[author.links]]
linkedin = "https://www.linkedin.com/in/cjhallau"
[[author.links]]
discord = "https://discord.com/users/700950024523350048"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false
# [[menu.footer]]
# identifier = "site-analytics"
# name = "Site Analytics"
# url = "https://analytics.0x40.me/share/Xf425O0N/0x40-me"
# weight = 1
[[menu.footer]]
identifier = "sitemap"
name = "Sitemap"
url = "/sitemap.xml"
weight = 2
[[menu.main]]
identifier = "IP"
name = "My IP"
target = "_blank"
url = "http://ip.pooper.net.au"
weight = 7
[[menu.main]]
identifier = "dig"
name = "Dig"
url = "https://dig.embr.workers.dev/"
weight = 6
[params]
colorScheme = "avocado"
darkToggle = "true"
[params.article]
dateFormat = "2 January 2006"
editAppendPath = true
editURL = "https://github.com/"
showAuthor = true
showBreadcrumbs = true
showDate = true
showDraftLabel = true
showEdit = false
showHeadingAnchors = true
showPagination = false
showReadingTime = true
showWordCount = false
[params.homepage]
layout = "profile"
showRecent = false
[params.list]
groupByYear = false
showBreadcrumbs = true
[taxonomies]
tag = "tags"
